name: Feature request
description: Suggest a new Feature to be added or replaced in DesQTA
labels: enhancement
type: "Feature"
title: "[FR]"

body:
  - type: checkboxes
    attributes:
      label: Confirm
      options:
        - label: "Is this feature request related to a Bug report?"
          required: false

  - type: input
    attributes:
      label: Bug report link
      description: "If this feature request is related to a bug report, please insert the link to the bug report here"
      placeholder: "https://github.com/BetterSEQTA/DesQTA/issues/..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Feature details
        Before you request a feature, [please search](https://github.com/BetterSEQTA/DesQTA/issues) if it has already been requested. (Make sure to check closed issues as well!)

  - type: dropdown
    attributes:
      label: Feature type
      multiple: false
      options:
        - Graphical
        - Functional
        - Not Sure
    validations:
      required: true

  - type: input
    attributes:
      label: Feature Details
      description: Please write, with as much detail as possible, what you would like to see from this feature.
      placeholder: It would be cool if...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional details
      description: Anything else that would help describe your vision (reference images, descriptions, etc)
    validations:
      required: false
